### ISSUE TITLE
Rendering PDFs

### ISSUE THREAD

**Issue by hfgolino** [quarto-dev/quarto-web#104]
Dear colleagues, while trying to render a PDF with Quarto, from RStudio, the following error shows up:

```
runnning pdflatex - 1
compilation failed- missing packages (automatic installed disabled)
```

I can't figure out how to modify the yml of Quarto to automatically install tex packages automatically, although I have tinytext installed.

Session info:
```
RStudio
2022.02.1 Build 461

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  fastmap_1.1.0   htmltools_0.5.2 tools_4.0.2    
 [5] yaml_2.2.1      rmarkdown_2.13  knitr_1.33      xfun_0.30      
 [9] digest_0.6.27   rlang_0.4.11    evaluate_0.14  
```

Any ideas?

**Comment by dragonstyle** [comment]
It seems as though quarto can’t find the texlive manager on your path- do you know how you installed tinytex? ( quarto will by default attempt to install missing packages as long as it can reach the `tlmgr`…

**Comment by hfgolino** [comment]
I have tinytex installed via R (I use it to compile PDF in Rmarkdown documents)...

**Comment by jjallaire** [comment]
One suspicious thing is that I see that `pdflatex` is being used for the compilation. Unless you set that explicitly this might mean that R Markdown is actually what is in use for the render (as Quarto uses xelatex by default).

**Comment by hfgolino** [comment]
I tried both xelatex and pdflatex...

The error is the same for both.

**Comment by jjallaire** [comment]
Okay, @dragonstyle do we know whether we have any issues w/ running against the R installed version of tinytex?

**Comment by hfgolino** [comment]
I uninstalled tinytex, and the issue persists...
Not really sure what to do.

Any help would be appreciated.

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* ***@***.***
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em sáb., 2 de abr. de 2022 às 21:26, J.J. Allaire ***@***.***>
escreveu:
