### ISSUE TITLE
🙋 Question: How does this project differ from Jupyter Book?

### ISSUE THREAD

**Issue by dynamicwebpaige** [quarto-dev/quarto-web#11]
Greetings, all!

Am not sure if this is the correct place to ask: but am curious how [`quarto-web`](quarto.org) differs from [Jupyter Book](https://jupyterbook.org/intro.html). The two projects feel very similar in motivation, and look near-identical. Are there any plans to collaborate on a standard format, or to ensure consistency / interoperability?

**Comment by jjallaire** [comment]
The biggest difference is that Quarto is based on Pandoc (https://pandoc.org/), and Jupyter Book is based on Sphinx / MyST (https://myst-parser.readthedocs.io/en/latest/). Both Pandoc and Sphinx are deep and powerful publishing systems, but they have totally different implementations / backends so are difficult to combine in a single project. 

Beyond the different backends, the approaches to extending markdown taken by MyST and Pandoc are quite divergent. Neither is really better or worse, but the Quarto team has a pretty deep existing investment in the Pandoc variant (including the development of a visual editor for Pandoc markdown, see https://rstudio.github.io/visual-markdown-editing/) so wanted to build on top of that. 

In principle it would be great to have a standard format, and in some ways for the Jupyter ecosystem we already have one (.ipynb files). However, the markdown processors are so different in syntax and philosophy that trying to make a single textual format that implements the full breadth of features of both systems would be near to impossible. You could definitely create converters, but they would likely converge to a lowest common denominator that might frustrate users.
