### ISSUE TITLE
Unlinked reference pages?

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-web#115]
I don't think we can find the following two pages because there are no links on the index.
Or is it linked from somewhere?

https://github.com/quarto-dev/quarto-web/blob/3cf6d76f011b11bed2d851fc1686151cfe6ab487/docs/reference/dates.qmd
https://github.com/quarto-dev/quarto-web/blob/3cf6d76f011b11bed2d851fc1686151cfe6ab487/docs/reference/globs.qmd

**Comment by jjallaire** [comment]
Thanks for pointing this out! Remedied here: https://github.com/quarto-dev/quarto-web/commit/1dbe917d266233a561b70a14ef63bc11bd550b80

**Comment by jjallaire** [comment]
Indeed! Thank you, just updated...
