### ISSUE TITLE
Documentation references wrong options?

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-web#117]
I think the documentation on this page is referencing the wrong options in some places.

https://quarto.org/docs/reference/formats/pdf.html

See attached images for details.
<img width="776" alt="Screen Shot 2022-04-10 at 19 23 34" src="https://user-images.githubusercontent.com/25734232/162646676-b12974c9-5c0a-4502-900a-dde80ca558e4.png">

**Comment by jjallaire** [comment]
Thanks so much for pointing this out! This has now been fixed.
