### ISSUE TITLE
The Data Binding Example is not working

### ISSUE THREAD

**Issue by scottfranz** [quarto-dev/quarto-web#138]
Hey this example combining Shiny and Observable is not working on your website.
https://jjallaire.shinyapps.io/data-shiny-ojs/

**Comment by jjallaire** [comment]
Thanks for the heads up! There were some changes in Observable that are resulting in an error (we just need to re-deploy with a more recent version of the library)

**Comment by jjallaire** [comment]
Thanks again for reporting this, it is now been updated to work correctly!

**Comment by scottfranz** [comment]
Thanks for making the example. Quarto is very fun to use!
