### ISSUE TITLE
Customizing Reveal Themes: Difference between Saas / Sass?

### ISSUE THREAD

**Issue by cathblatter** [quarto-dev/quarto-web#140]
I noticed in the documentation here https://quarto.org/docs/presentations/revealjs/themes.html#customizing-themes 

that sometimes there is written 'Sass' (directing to [Sass-language](https://sass-lang.com/)) but later on there is a link to all variables, entitled 'Saas': https://quarto.org/docs/presentations/revealjs/themes.html#saas-variables

I tried to google it to no avail - Is there a difference between 'Sass' and 'Saas'? (or just a typo?) 

Thanks

**Comment by dragonstyle** [comment]
Definitely just a typo! I will fix today- thanks for letting us know...

**Comment by dragonstyle** [comment]
This should be fixed- thanks again!
