### ISSUE TITLE
Two bad elephant links

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-web#142]
Trying to learn/understand markdown and html by going through your site. 

However, the elephant links [here](https://quarto.org/docs/authoring/markdown-basics.html) confuse me. The images in the 4th, 5th, and 6th rows purportedly should go to https://quarto.org, but only the 6th goes there -- the images in rows 4 and 5 instead go to https://quarto.org/quarto.org which gives "Page Not Found".

If I understand it, the underlying code should be [here](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/markdown-basics.qmd), lines 66-80. Those lines work correctly for me if I copy them to a qmd file and use a dummy image.  Lines 75 and 77 (rows 4 and 5) only have a single slash in the link (https:/quarto.org) rather than two, but that still works fine in my qmd file, so I don't know what's up but I figured I'd let you know.

**Comment by jjallaire** [comment]
Thanks for the heads up! Those links were incorrectly specified (as you said w/ `/` rather than `//`). This is now fixed.
