### ISSUE TITLE
if (!require("palmerpenguins")) install.packages("palmerpenguins") in hello.qmd

### ISSUE THREAD

**Issue by aito123** [quarto-dev/quarto-web#164]
Hello Quarto,
Huge fan coming from R. I'm starting to make the transition to `.qmd` and i realize that if the user doesn't have installed `palmerpenguins` you can't Render hello.qmd file. Someone with basic experience in R could easily install palmerpenguins and maybe also tidyverse, though could be a disappointment for someone new so i recommend the following:

```
if (!require("palmerpenguins")) install.packages("palmerpenguins")
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
library(palmerpenguins)
```

I'm more a fan of `pacman` package so maybe only require pacman and then p_load the other packages. In either case, is more smooth for someone new. Anyway, let me know.

Greetings from Perú,
Santiago

**Comment by jjallaire** [comment]
Thanks! I've added instructions to install these packages to the tutorial: https://quarto.org/docs/get-started/hello/rstudio.html

**Comment by aito123** [comment]
Glad to help.
