### ISSUE TITLE
Problem when rendering the website ojs example

### ISSUE THREAD

**Issue by Pierre9344** [quarto-dev/quarto-web#178]
Hello,

I try to  create some html page with ojs charts. When I render them, VS Code show me a preview that render correctly the charts. But if I try to open the generated html file (I use firefox), it doesn't contain any ojs chart:

![2022-05-25_091545](https://user-images.githubusercontent.com/86181677/170203241-ef916d00-9a4f-4be8-af26-2a680711bbea.png)

However, if I try use the localhost address that VS Code indicate upside the preview inside firefox, it show the document with the charts.

![2022-05-25_091729](https://user-images.githubusercontent.com/86181677/170203780-0a097bc5-0c8d-4c7a-bfeb-47c3ac7a07e4.png)

I have the same problem with the qmd files from the website: [penguins.zip](https://github.com/quarto-dev/quarto-web/files/8768763/penguins.zip)

Do you have any idea about what I do wrong?

I thank you in advance for your answer.

**Comment by Pierre9344** [comment]
Sorry for the double post, I found the problem. I need to set the html option self-contained to true.

**Comment by jjallaire** [comment]
@cscheid AFAIK this shouldn't require self-contained. Could you take a look at this to make sure there is nothing unexpected on our end?
