### ISSUE TITLE
Is there a way to number the sections: 1. Section A instead of 1 Section A ?

### ISSUE THREAD

**Issue by aito123** [quarto-dev/quarto-web#188]
Hello, 
When i'm render a Quarto Blog to MS Word Output it appears to number the sections this way:

e.g 1 Introduction
 
![image](https://user-images.githubusercontent.com/53672503/170839263-6b9afa23-8b91-475e-ad8d-9444c991e6f0.png)

I was wondering if there is a way to change a parameter and render sections this other way:

e.g 1. Introduction
![image](https://user-images.githubusercontent.com/53672503/170839309-1278c318-4305-4282-b81a-3acbdcc50e70.png)

I'm rendering the demo quarto book that appears when you firts create a quarto book project.

Regards

**Comment by jjallaire** [comment]
We don't currently have a way to customized that. However, in looking into this issue I noticed that when pandoc numbers word sections it uses a tab to provide some horizontal air:

<img width="887" alt="Screen Shot 2022-05-31 at 5 45 12 PM" src="https://user-images.githubusercontent.com/104391/171289684-18fcdcf5-c434-4949-8581-4dfe86daa79f.png">

If our numbering matched Pandoc's behavior (which it probably should in any case) would that address some of what you are trying to accomplish w/ this issue?

**Comment by jjallaire** [comment]
I changed the default behavior for docx to use "1. Chapter" rather than "1 Chapter" here: https://github.com/quarto-dev/quarto-cli/commit/4206bcf432f33e868ae60b0ab7ceb3a9a09e2f91. It should ultimately be configurable but in the meantime the form you suggest is I think preferable.
