### ISSUE TITLE
Unable to display tables as part of a panel tabset in Jupyter lab

### ISSUE THREAD

**Issue by salestial** [quarto-dev/quarto-web#193]
Hi

I am unable to use the `panel: tabset` functionality in Jupyterlab. For example, the following cell in a Jupyter notebook produces the tables but no panels:

```
#| panel: tabset

## Hello

import pandas as pd
display(pd.DataFrame({"A": {1: "I"}}))


## World

display(pd.DataFrame({"B": {2: "II"}}))
```

If I use the markdown equivalent, it produces the panels but not the tables (simply prints out the source):

::: {.panel-tabset}

## Hello

```{python}
import pandas as pd
display(pd.DataFrame({"A": {1: "I"}}))
```

## World

```{python}
import pandas as pd
display(pd.DataFrame({"B": {2: "II"}}))
```

:::

Kindly help.

Thanks.

**Comment by jjallaire** [comment]
For `.ipynb` you need to break the content across multiple markdown and code cells. For example:

<img width="725" alt="Screen Shot 2022-05-31 at 7 55 53 PM" src="https://user-images.githubusercontent.com/104391/171302344-f9ea71ef-7888-47d4-8e28-413841ca7b19.png">

For `.qmd` I am getting the correct tabbed output with the following input:

````markdown
::: {.panel-tabset}

## Hello

```{python}
import pandas as pd
display(pd.DataFrame({"A": {1: "I"}}))
```


## World

```{python}
import pandas as pd
display(pd.DataFrame({"B": {2: "II"}}))
```

:::
````

**Comment by salestial** [comment]
Beautiful - thank you! I will have a go.

**Comment by salestial** [comment]
Worked perfectly - thanks!
