### ISSUE TITLE
tbl-cap-location not working

### ISSUE THREAD

**Issue by Athanasiamo** [quarto-dev/quarto-web#197]
Hi.

I've been trying to relocate the table captions without luck. Whatever I try, the table caption location remains at the top.

````
---
title: "Untitled"
format: pdf
editor: visual
---

some text @tbl-mtcars\
\

```{r}
#| label: tbl-mtcars
#| tbl-cap: My caption
#| tbl-cap-location: bottom

knitr::kable(mtcars[1:10,1:4], digits = 2, booktabs = TRUE)

```

````

![image](https://user-images.githubusercontent.com/14014329/171106671-e5692e59-67cd-49e1-8e23-56ab22043aad.png)

What am I missing here?

**Comment by dragonstyle** [comment]
This should be working as of:

[quarto-cli#2bfe2d602142c60225ab69181cab4d849ffa28cd](https://github.com/quarto-dev/quarto-cli/commit/2bfe2d602142c60225ab69181cab4d849ffa28cd)

A fresh release is on the way.

**Comment by Athanasiamo** [comment]
Looking forward to that! Thanks!

**Comment by Athanasiamo** [comment]
right, can confirm that this works as a global setting on my end now :) The caption positions (table and figure) do also pop-up as a possible per-cell settings too (with pipe hash). I dont know if that is intended or not, but it gives the impression that this can be set on a per cell basis, which it cant. At least not now.

**Comment by jjallaire** [comment]
I think `tbl-cap-location: margin` might still work at a cell level. @dragonstyle is that correct? If so we should probably update our completion handler to either show just what's available (or if that's not possible due to conflict w/ the global option just exclude it prevent confusion)

**Comment by dragonstyle** [comment]
Yes that is correct- margin is available per cell. I can update completions...

**Comment by jjallaire** [comment]
It's possible that the completions are shared w/ document level (and there isn't really a good way to separate this). In that case maybe just remove from cell level (you'd have to take it completely out of where it is now and stick it in a document bucket)
