### ISSUE TITLE
Question: pandoc divs to wrap Bootstrap components in docs site?

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-web#2]
I understand the irony of me asking this here 😆 I'm happy to add this info to the docs, but I don't yet know if these two things are possible with pandoc divs instead of raw HTML (which I have working):

+ Insert two columns (https://getbootstrap.com/docs/5.0/layout/columns/)

+ Insert tabbed sections (https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs)

**Comment by jjallaire** [comment]
Docs moved over here: https://quarto.org/docs/output-formats/html-basics.html#tabsets
