### ISSUE TITLE
Broken link to trademark policy on licence page

### ISSUE THREAD

**Issue by StuieT85** [quarto-dev/quarto-web#201]
Good Afternoon

The link to the trademark policy in the body of https://quarto.org/license.html points to localhost rather that https://quarto.org/trademark.html

If it helps I can see what is wrong on https://github.com/quarto-dev/quarto-web/blob/main/_site/license.html on line 196 but I am not very confident with git so am not able to send a pull request. Sorry

**Comment by jjallaire** [comment]
Thanks for letting us know! Just fixed....
