### ISSUE TITLE
Shortcode <include> not working

### ISSUE THREAD

**Issue by drfurtado** [quarto-dev/quarto-web#204]
I cannot get the `include` to work.

doc1.qmd
Blah Blah

doc2.qmd
{{< include _doc1.qmd >}}

Upon rendering `doc2`, nothing happens; not even an error message. Basically, `doc1` does not show in `doc2`. The shortcode is shown:

{{< include _doc1.qmd >}}

Thank you!!!

**Comment by jjallaire** [comment]
The file names don’t match (`doc1.qmd` vs. `_doc1.qmd`)

**Comment by drfurtado** [comment]
> The file names don’t match (`doc1.qmd` vs. `_doc1.qmd`)

Thanks for the quick response. 
I changed `doc1.qmd` to `_doc1.qmd` but the result was the same.

**Comment by jjallaire** [comment]
You may be running an older version of Quarto that doesn't yet have `include`. What version are you running?

All of our include related tests are currently passing so the feature definitely works. If you are running the latest version and continue to have an example where things don't work as expected then pls create a minimum reproducible example in a git repo and post that link here.

**Comment by jjallaire** [comment]
Yes, that example works for me fine with the latest version of Quarto.

Please update your version of Quarto here (https://quarto.org/docs/get-started/) and things will work as expected.

**Comment by drfurtado** [comment]
> Yes, that example works for me fine with the latest version of Quarto.
> 
> Please update your version of Quarto here (https://quarto.org/docs/get-started/) and things will work as expected.

Indeed, I thought that updating RStidio would update Quarto. Sorry for the confusion and many thanks.
