### ISSUE TITLE
Citable article appendix Bibtex citation overflow on phone screen

### ISSUE THREAD

**Issue by drganghe** [quarto-dev/quarto-web#216]
Thank you Quarto team for creating this tool, I tried and I love it.

I recently found that the Bibtex citation appendix in citable articles overflow on phone screen, and this seems to block Google from indexing the pages.
https://quarto.org/docs/authoring/create-citeable-articles.html

See below the screenshot.
![IMG_3918](https://user-images.githubusercontent.com/4475421/173187286-39f82669-6f2b-483b-adc9-3af2d98e76d4.jpg)

Any fix on this or am I using the old version?

**Comment by dragonstyle** [comment]
Thanks for letting us know! I have fixed this and it should be available in the latest release in a few minutes. Please report issues in the `quarto-dev/quarto-cli` repo unless the issue is with the document/website itself. TY!

**Comment by drganghe** [comment]
Wow, this is a quick fix. Thanks. Sorry I was on the page link search a solution and submit an issue. Next time I will use the repository you shared. Please feel free to delete my reports here.

**Comment by dragonstyle** [comment]
No worries at all - just glad to have the report either way! Thank you for letting us know.
