### ISSUE TITLE
Removing margin sidebar

### ISSUE THREAD

**Issue by owiecc** [quarto-dev/quarto-web#217]
Is there a way to remove the margin sidebar? To be clear, I mean the `On this page` navigation. I could not find any solution in the [Website Navigation documentation](https://quarto.org/docs/websites/website-navigation.html).

**Comment by dragonstyle** [comment]
One thing you could try is `page-layout: full`, which will allow the body region to expand into the sidebar region if content is not placed in the margin. More here (though I understand this is probably hard to find based upon the problem you were trying to solve). 

https://quarto.org/docs/output-formats/page-layout.html#full

**Comment by owiecc** [comment]
I like the margin and I would like to use it for content/figures/notes. I am going for a clean layout and would like to get rid of most of the navigation. I will probably just disable that in custom CSS for now. 

As there is an easy way to [hide the main navigation panes](https://quarto.org/docs/websites/website-navigation.html#hiding-navigation) I feel there should be an eqivalen switch for margin sidebar also.

**Comment by dragonstyle** [comment]
Oh - sorry I just realized exactly what you're trying to disable! The 'On this page' is the table of contents for the document, so you can disable that explicitly using `toc: false`.

**Comment by owiecc** [comment]
That works like a charm. I checked the HTML but I missed there is more stuff under `<div id="quarto-margin-sidebar">`. If i looked closer I would have found `<nav id="TOC">`. Thanks!
