### ISSUE TITLE
Publishing using Netlify

### ISSUE THREAD

**Issue by pstata** [quarto-dev/quarto-web#221]
I am trying to create my first Blog using Quarnto , was able to create example blog on local host, I have following structure , I have copied index.html from _site folder as netlify do not know where to find the Index file , not sure what' going on , can you help me with Netlify settings as I am getting 404 error when deployed to 

![image](https://user-images.githubusercontent.com/107627844/174143576-d4a17583-a016-4a5a-8061-bbb702d5b9ae.png)

**Comment by jjallaire** [comment]
Please see the documentation here: https://quarto.org/docs/websites/publishing-websites.html#netlify
