### ISSUE TITLE
matplotlib-demo code on quarto.org broken

### ISSUE THREAD

**Issue by skadauke** [quarto-dev/quarto-web#24]
Working my way through the quarto docs, I got stumped by the `matplotlib-demo.qmd` code on the Welcome page.

The following part in the demo refers to `index_files/figure-html/fig-polar-output-1.png` which isn't getting generated after invoking `quarto render matplotlib-demo.qmd`.

```
::: {.cell-output-display}
![A line plot on a polar axis](index_files/figure-html/fig-polar-output-1.png){#fig-polar width=442 height=432}
:::
```

I was surprised to find that `quarto-web/index.qmd` actually has an updated version of the `matplotlib-demo.qmd` code that doesn't have this section and works great. But `quarto-dev/quarto-web/blob/main/_site/index.html` contains the broken code.

Perhaps the site needs to be rebuilt and redeployed?

Thanks for all the awesome work y'all are doing.

**Comment by jjallaire** [comment]
Thanks for reporting! Yes, I think this was transitory and fixed with a site regen.
