### ISSUE TITLE
GitHub Actions workflow seems broken

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-web#275]
It seems to be looping.
https://github.com/quarto-dev/quarto-web/commit/a56e95665d26aba52c7b151085ab9ec3f4e25299
https://github.com/quarto-dev/quarto-web/commit/6279526d5b5c77b1646ff15813761ff34b63131b

**Comment by jjallaire** [comment]
@cscheid Could you take a look at this?

**Comment by cscheid** [comment]
We've looked a bit further on this, and these workflows are being run manually on purpose. We still don't understand why the checksums are changing, but to our current understanding, gha's are not currently looping.
