### ISSUE TITLE
Navigation from top level pages of Interactive Docs sections doesn't work

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-web#29]
If you click on "Observable JS" or "Shiny" on the sidebar of [this page](https://quarto.org/docs/interactive/), you'll be sent to the index of that section. However, the navigation link on the bottom of these pages won't take you to the next page. 

### To reproduce:

1. Go to either of:
  * [Interactive Docs > Observable JS > Introduction](https://quarto.org/docs/interactive/ojs/)
  * [Interactive Docs > Shiny > Introduction](https://quarto.org/docs/interactive/shiny/)
1. Use the "Introduction" link at the bottom of either page. You'll be redirected back to the same page you're on. 

This link should point to the next section, but it is currently pointing to itself. This seems to be because the doc is put as the `- section` value instead of a string:

https://github.com/quarto-dev/quarto-web/blob/575978dca10a5e432dcd4b2cdb79d7a5ec594c0b/_quarto.yml#L85

https://github.com/quarto-dev/quarto-web/blob/575978dca10a5e432dcd4b2cdb79d7a5ec594c0b/_quarto.yml#L111

**Comment by dragonstyle** [comment]
Fixed here, not yet merged to main.

https://github.com/quarto-dev/quarto-cli/commit/4b244d539cbd51bd0fcc7af475bbfb1760f69bc8
