### ISSUE TITLE
FR: add previous/next item in section buttons

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-web#3]
When inside a section, it is nice to have navigation at the bottom of each item to see the previous/next item in the section so you can navigate linearly without the sidebar toc.

Seen in action here https://www.tidymodels.org/start/recipes/#session-info: 
<img width="1197" alt="Screen Shot 2021-04-05 at 4 06 09 PM" src="https://user-images.githubusercontent.com/12160301/113620888-e765d180-9628-11eb-9156-e3dd8de5d0b5.png">

**Comment by jjallaire** [comment]
Now implemented, docs here: https://quarto.org/docs/websites/website-navigation.html#page-navigation
