### ISSUE TITLE
PDF compilation LaTeX requirements

### ISSUE THREAD

**Issue by prubin73** [quarto-dev/quarto-web#302]
The authoring tutorial launches into an example of compiling a PDF document without any warning to the reader that they will require a LaTeX installation (nor any description of alternatives to LaTeX). It also defaults to using xetex. On my system (where I have TeXLive installed and use pdflatex), an attempt to render the sample document prompted something (pandoc?) to attempt to install xelatex _without permission_. (It failed.)

After some sleuthing, I found the YAML header option `pdf-engine: pdflatex` which allowed the document to be compiled. The reader should be alerted to dependencies and to compilation alternatives before going too far down the rabbit hole.

**Comment by jjallaire** [comment]
@mine-cetinkaya-rundel I ended up taking the example code for rendering PDFs out of the VS Code and Jupyter Lab tutorials b/c of precisely this issue. I wonder if we should do the same for R? (the idea being that we don't encourage the user to type a command that might well fail and that we wait until they are reading the PDF docs to introduce the notion of the other dependencies required)

**Comment by mine-cetinkaya-rundel** [comment]
That makes sense @jjallaire. Removing any reference to `pdf` would get rid of much of the content in the [Output Formats section](https://quarto.org/docs/get-started/authoring/rstudio.html#output-formats), which doesn't seem ideal.

One option (1) is to rewrite that section with an output format that doesn't have dependencies, e.g. `revealjs`, and mention `pdf` and `docx` in a short statement in passing.

The other option (2) is to leave the screenshots and much of the narrative as is, just take out the action sentences like "do this now".

(1) seems nicer maybe but I can't quite see without writing it if it would open other cans of worms that lengthen the narrative. (2) is definitely an easy fix.

**Comment by jjallaire** [comment]
@mine-cetinkaya-rundel For the time being I've added docs on installing TinyTeX to the tutorial: https://github.com/quarto-dev/quarto-web/commit/cd74fa5d0739b82a275246a3dca04c57ef05b5bd

If you think this is likely to result in users getting hitched up on the install feel free to modify the tutorial to either discourage rendering or use docx/reveal as you suggested. I'm closing this but feel free to re-open if you want to make changes here.
