### ISSUE TITLE
Quarto authoring tutorial: Render menu

### ISSUE THREAD

**Issue by prubin73** [quarto-dev/quarto-web#303]
After discussing multiple formats, the rendering tutorial has the user render the document (using the first format listed in the header) and then discusses how to render multiple formats using the quarto CLI. It might be worth mentioning here that the Render toolbar button in RStudio has a drop-down selection that lets the user switch formats and re-render (albeit one format at a time).

**Comment by jjallaire** [comment]
Thanks for the suggestion! Implemented here: https://github.com/quarto-dev/quarto-web/commit/0762fdfb20f82e3f41f667f5bf838e8539f5c5c7
