### ISSUE TITLE
Add "terminal" chunk label to all terminal code chunks

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-web#315]
Some feedback from learners and workshop attendees. There was a bit of confusion from folks who were not used to using the terminal. It may be useful to append the `terminal` tag via the `code-filename` extension, to documentation locations when commands like `quarto render` are used.

This would make it more clear when switching between the terminal and the R/Python REPL.

**Comment by jjallaire** [comment]
Good idea! Done here: https://github.com/quarto-dev/quarto-web/commit/5a79cba1d466d55da139cd447c9f3fe1fc812d4d
