### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-web#32]
This link: https://github.com/quarto-dev/quarto-cli/blob/main/design/quarto-themes.md appears to be broken.

https://github.com/quarto-dev/quarto-web/blob/28c79d3fe3e828cd1e68a2faa2e6a5df5c1dd3a0/docs/output-formats/html-themes.qmd#L106

**Comment by jjallaire** [comment]
Thx! Updated with a link to a version of that doc hosted on the site.
