### ISSUE TITLE
Quarto Pub 401 authentication error

### ISSUE THREAD

**Issue by carobuck** [quarto-dev/quarto-web#321]
Get this error: "ERROR: API Error: 401 (Unauthorized)" (despite being successfully logged in to quartopub.com in default browser) when attempting to publish a single .qmd via CLI as follows: quarto publish quarto-pub filename.qmd 

Need better documentation for how to (force) authentication if it doesn't work automatically.

**Comment by jjallaire** [comment]
Thanks for reporting this, in v1.1 we should now be automatically prompting for re-auth here: https://github.com/quarto-dev/quarto-cli/commit/49b5046ff8be6ff60d1b8043245dacad36e31151
