### ISSUE TITLE
Add Quarto Pub to publishing Tab and expand on authentication

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-web#326]
Per a [user request]((https://twitter.com/ellamkaye/status/1557992095054536704?s=20&t=vwy6DsfAhsai7kXLDJ3FQg)) from @EllaKaye

- Expand on Quarto Pub authentication and process for adding multiple credentials via CLI 
  - Requires logging out of QuartoPub site and logging into additional accounts and then repeating auth flow
  - Expand on managing credentials/where to find
  - Expand on access keys -> non-interactive auth
- Add Quarto Pub "stub" to left sidebar underneath Publishing section
- Add left sidebar to Quarto Pub article (it currently doesn't have any left sidebar)

**Comment by jjallaire** [comment]
Improved documentation now available here: https://quarto.org/docs/publishing/quarto-pub.html

**Comment by EllaKaye** [comment]
Thanks @jjallaire! That's really helpful in clarifying the issue around multiple accounts.
