### ISSUE TITLE
"Theme Options" section links to a wrong Bootstrap document?

### ISSUE THREAD

**Issue by yutannihilation** [quarto-dev/quarto-web#330]
[Theme Options section on HTML Theming page](https://quarto.org/docs/output-formats/html-themes.html#theme-options) describes:

> You can see all of the variables here:
> 
> https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss

but this variable in the next section cannot be found on the linked `_variables.scss` (there's `$font-size-h2`).

``` css
$h2-font-size:          1.6rem !default;
```

I guess `twbs/bootstrap-sass` is for Bootstrap 3 while Quarto actually uses Bootstrap 5?

**Comment by yutannihilation** [comment]
This one?

https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss

**Comment by dragonstyle** [comment]
Thanks for reporting this- just fixed it to use the correct URL- thank you!

**Comment by yutannihilation** [comment]
Thanks!
