### ISSUE TITLE
License of this repository?

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-web#332]
It would be great if you could describe this repository (the contents of the documentation and the source code contained in this repository).

**Comment by epijim** [comment]
They talk about Quarto itself here: https://github.com/quarto-dev/quarto-web/blob/main/license.qmd

Not sure if that refers to the docs site as well though, as it talks about quarto source code. But I guess it's implied?

**Comment by jjallaire** [comment]
Yes that is implied (you can see this if you click on the "License" link in the quarto-web repo on GitHub)
