### ISSUE TITLE
Another example for the gallery (book section)

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/quarto-web#334]
If you are interested, for this section of the gallery: https://quarto.org/docs/gallery/#books

I created templates and instructions for creating template partials in order to create custom title page designs for PDFs. Doesn't use any special LaTeX packages or anything so should be quite robust to different engines and document classes. This is useful for anyone who creates books with Quarto and needs the PDF to have a highly customized title page.

https://nmfs-opensci.github.io/quarto_titlepages/

![image](https://user-images.githubusercontent.com/2545978/184684045-19b485d9-2895-4e80-ab3e-214c8d83bb9e.png)

**Comment by jjallaire** [comment]
This has indeed been added to the gallery, thanks!
