### ISSUE TITLE
example showing how to access parameters

### ISSUE THREAD

**Issue by borkovec** [quarto-dev/quarto-web#340]
Maybe add an example of how to access the parameters in the code... took me a moment to figure it out ;)
I know, it's probably the same as in markdown, but not every quarto user will be familiar with markdown

``````
---
engine: knitr
execute:
  echo: false
format:
  html:
    self-contained: true
    toc: true
params:
  test_param: "test"
---


```{r}
#| echo: true

library(reticulate)

print("I'm R")
print(params$test_param)
```

```{python}
#| echo: true

print("I'm python")

print(r.params["test_param"])
```
``````

https://quarto.org/docs/computations/parameters.html

**Comment by jjallaire** [comment]
Thanks for pointing this out! Examples added here: https://github.com/quarto-dev/quarto-web/commit/c006dabf630c1e65e3edc53ad64b08ba75265a9b
