### ISSUE TITLE
How to structure a video gallery page similarly to RStudio's webinar page?

### ISSUE THREAD

**Issue by ashirwad** [quarto-dev/quarto-web#341]
Hello,

I am trying to use Quarto's [custom listings feature](https://quarto.org/docs/websites/website-listings-custom.html) to create a video gallery page structured similarly to [RStudio's webinar page](https://www.rstudio.com/resources/webinars/). As I understand it, I will first have to create an `ejs` template. However, I have limited experience with `html`, `css` & `javascript` to create everything from scratch. Is the `ejs` template for RStudio's webinar page publicly available for me to take some inspiration? 

Thanks!

**Comment by dragonstyle** [comment]
I'm not sure about how that specific page is generated, but I think that a good place to start would be using the existing support for a grid style layout and just use metadata files to populate the grid. This discussion:

https://github.com/quarto-dev/quarto-cli/discussions/1840

should be a good starting place - by providing the correct metadata fields you can you just use the existing grid style layout and its features to get the appearance that you'd like.
