### ISSUE TITLE
Broken Links Under Multiple Figues (Figure and Article Layout links)

### ISSUE THREAD

**Issue by rfkova** [quarto-dev/quarto-web#342]
As title indicates, clicking [Figure Layout](https://tutorial.quarto.org/docs/authoring/figure-layout.html) or [Article Layout](https://tutorial.quarto.org/docs/authoring/article-layout.html) drops me on a "couldn't find that site"-style error in my browser.

**Comment by jjallaire** [comment]
Thanks! Addressed here: https://github.com/quarto-dev/quarto-web/commit/33512e80ed5cf4272f910d44d6bb133d2bce8424
