### ISSUE TITLE
Broken hyperlink code

### ISSUE THREAD

**Issue by RaymondBalise** [quarto-dev/quarto-web#344]
This line

```
[! [Caption](elephant. png)] (https: //quarto.org "An elephant")
```

which is on the page: <https://quarto.org/docs/authoring/markdown-basics.html> generates a hyperlinked image with a tooltip.  This is completely cool but when clicked the link takes the user to the quarto home page with an error saying:  

```
Page Not Found
The page you requested cannot be found (perhaps it was moved or renamed).
You may want to try searching to find the page's new location.
```

Is there a way to avoid the problem?

**Comment by andrewpbray** [comment]
I think you found a typo. I tried fixing it here: <https://github.com/quarto-dev/quarto-web/pull/345>

ps: good to see you Ray!
