### ISSUE TITLE
Error in documentation about syntax highlighting for html code

### ISSUE THREAD

**Issue by EmilHvitfeldt** [quarto-dev/quarto-web#346]
The following section on the website: https://quarto.org/docs/output-formats/html-code.html#custom-highlighting See screenshot:

<img width="789" alt="Screen Shot 2022-08-19 at 9 18 13 PM" src="https://user-images.githubusercontent.com/14034784/185691669-e9f8e359-3aa1-4c2c-862f-e4768f838a0e.png">

doesn't align with the intended documentation

https://github.com/quarto-dev/quarto-web/blob/6704f46480d6f3242191f676142de9d76708e639/docs/output-formats/html-code.qmd#L289-L299

**Comment by jjallaire** [comment]
Thanks! Resolved here: https://github.com/quarto-dev/quarto-web/commit/478cfccd07f842dc504a24df08b9837bd6503f42
