### ISSUE TITLE
Plotly fails to plot when saved as a quarto notebook

### ISSUE THREAD

**Issue by amkhosla** [quarto-dev/quarto-web#351]
open tutorial computations.ipynb
run quarto preview computations.ipynb
plotly plot fails to show.

**Comment by amkhosla** [comment]
fix: add line

plotly.offline.init_notebook_mode(connected = False);

**Comment by jjallaire** [comment]
That notebook is unexecuted so there is indeed no output shown by default (the tutorial walks through executing the cells in JupyterLab after which you'd see the output show up). Note you can also do this non-interactively with:

```bash
quarto preview computations.ipynb --execute
```
