### ISSUE TITLE
RStudio-based tutorial gives frequent cryptic errors if not in a project

### ISSUE THREAD

**Issue by jhchou** [quarto-dev/quarto-web#365]
In the [RStudio-based computations tutorial](https://quarto.org/docs/get-started/computations/rstudio.html), there are frequent rather cryptic errors when attempting to run the supplied .qmd documents if it is done _outside_ of a project.

You may wish to update the beginning of the tutorial to specify that it should be run within a project. Currently, the instructions state:

> If you would like to follow along step-by-step in your own environment, download the Quarto document (.qmd) below, open it in RStudio, and click on  Render (or use the keyboard shortcut ⇧⌘K).

New users who don't know better and follow the directions exactly will get rather confused.

**Comment by cscheid** [comment]
Thanks for the feedback. I just followed the instructions on that webpage on a clean RStudio session without a project and didn't see any errors. Please do reopen this issue with a complete set of instructions that causes the errors you're seeing.
