### ISSUE TITLE
For authoring tutorial, add sample references.bib file to allow rendering

### ISSUE THREAD

**Issue by jhchou** [quarto-dev/quarto-web#366]
In the [tutorial](https://quarto.org/docs/get-started/authoring/rstudio.html), rendering fails without a `references.bib` file.

Suggest adding a link to a sample `references.bib` file to allow the tutorial document to render.

**Comment by cscheid** [comment]
As users follow the tutorial, the `references.bib` file will be automatically created by RStudio.
