### ISSUE TITLE
Translating terms in a webpage created with Quarto

### ISSUE THREAD

**Issue by beatrizmilz** [quarto-dev/quarto-web#38]
Hello again!

I'm using quarto for the first time on a webpage of a summer course about R markdown 😄  that I'm going to teach at the university.  There is no code for now because the course did not started yet. 

Since I speak Portuguese (and also the students in the course), I was trying to find in the website/documentation information about translating some English terms in the webpage to Portuguese.

For example (I circled it with purple) https://beatrizmilz.github.io/2022-curso-de-verao-ime-usp-relatorios/informacoes-gerais.html

<img width="1428" alt="Captura de Tela 2021-10-29 às 15 33 24" src="https://user-images.githubusercontent.com/42153618/139485345-12bcd2cc-1bb1-4be4-bc66-3b63e5661b46.png">

<img width="1436" alt="Captura de Tela 2021-10-29 às 15 34 19" src="https://user-images.githubusercontent.com/42153618/139485259-7c4c389a-2a5f-4e6f-bc6a-f0d25d833770.png">

Do this option to change the text language exists and I did not find it in the docs? (if it exists, sorry... if anyone has any links that I can read about it, I would be grateful)

If it is not possible, this is something in the roadmap for Quarto? (and in this case, this would probably not be related to the quarto-web repo) 
This feature does not seem like a "priority", a lot of people can interact with the webpage as it is. But Quarto seems like a great tool and I think, in the long run, it would be good to have options to have the whole website in our native languages in order for the Latin American community to use it more (since we mostly speak and create content in Spanish and Portuguese, and there is a lot of people here that does not speaks English).  

Thank you for your attention :)

**Comment by jjallaire** [comment]
There isn't currently a way to make most of these customizations however I think it's a high priority to do so. There aren't very many places where we inject language so it won't be terribly much effort to make them all customizable. Note that I believe you can customize the table of contents title ("On this page") with the `toc-title` option.

**Comment by jjallaire** [comment]
For callouts, if you include a custom caption (via a header as the first element of the callout) that will take care of those instances. @dragonstyle I tried setting a global `callout-appearance: minimal` which I believe should have eliminated all default captions but that didn't work -- should it have?

**Comment by beatrizmilz** [comment]
Thank you, JJ for your answer!  Happy to know that the option to use Quarto in different languages is a priority :)


I tried the `toc-title` option and it worked! 🎉  ( https://github.com/beatrizmilz/2022-curso-de-verao-ime-usp-relatorios/blob/ecea8c0fb724050366aa2b1d1cd2e818cc21878f/_quarto.yml#L41 ) 

I used the search in the docs and this info is there (so... sorry! I should had figured it out with the docs https://quarto.org/docs/output-formats/pdf-basics.html#table-of-contents )

The next thing that I think would be nice would be translating the text in the callouts, but reading more carefully the docs, is already there: https://quarto.org/docs/authoring/callouts.html#markdown-syntax 
> "note that the first markdown heading used within the callout is used as the callout heading"

So I fixed that on the website that I am creating as well, thanks!

That leaves only the texts in the search tool. I tried to tweak this file https://github.com/beatrizmilz/2022-curso-de-verao-ime-usp-relatorios/blob/36d69f76235482d73d957a254d0bae33186b4526/docs/site_libs/quarto-search/quarto-search.js#L290 but this file always gets overwritten (and returns to the original version) when I render the site, so I'm not sure how I could change these texts. If I find something out, I'll write in this thread.

I'm not sure if this thread should stay open or be closed. But thanks again for your help, JJ!

**Comment by jjallaire** [comment]
The only way to change the text in the search tool would be fork quarto and run from the forked version.

Let's keep this issue open and hopefully we'll provide a more complete solution soon!

**Comment by dragonstyle** [comment]
> For callouts, if you include a custom caption (via a header as the first element of the callout) that will take care of those instances. @dragonstyle I tried setting a global `callout-appearance: minimal` which I believe should have eliminated all default captions but that didn't work -- should it have?

Yes it should have. I just double checked that it appears to be working locally for me when testing in a simple book project and a simple html page. Anything special about the way you were setting it that might give me a clue?

**Comment by jjallaire** [comment]
Trying again this does indeed work! Here is my example:

```markdown
---
title: "Callout"
format: html
callout-appearance: simple
---

::: callout-note
This is a minimal callout.
:::
```

@beatrizmilz That config would result in no default captions for any of your callouts. `callout-appearance: minimal` would eliminate the icon and the caption.

**Comment by jjallaire** [comment]
We've put in the infrastructure for localized language text. More details are here: https://quarto.org/docs/authoring/language.html

Currently we have English, Chinese, and French translations (and we are working on a few more including German and Spanish).You can also provide your own translation if the language isn't yet supported.

 @beatrizmilz if you want to contribute a Portuguese translation details on how to do this are here: https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language

**Comment by beatrizmilz** [comment]
Hi @jjallaire ! I read the details on how to contribute with the Portuguese Translation and I'm going to do a PR soon! Thank you and Quarto team to consider this issue!

**Comment by jjallaire** [comment]
Great, thank you!!!
