### ISSUE TITLE
Bad copy-paste of @ from https://quarto.org/docs/get-started/computations/rstudio.html

### ISSUE THREAD

**Issue by GC22161** [quarto-dev/quarto-web#385]
A copy-paste 
from 
https://quarto.org/docs/get-started/computations/rstudio.html
of 
@fig-scatterplot shows a positive, strong, and linear relationship between the city and highway mileage of these cars.
in the visual editor of R Studio
introduce a backslash before @ as
\@fig-scatterplot shows a ...

As result, \@ is interpreted as raw text.

Thanks for your job,

**Comment by cscheid** [comment]
Thanks for your feedback.

That block is showing the source code. That's not a bad copy-paste, that's a quote.
