### ISSUE TITLE
suggestion for the Quarto Julia help webpage

### ISSUE THREAD

**Issue by RoyCCWang** [quarto-dev/quarto-web#389]
I have the following suggestions for [this help webpage](https://quarto.org/docs/computations/julia.html):

- Please add an extra sentence near the first example script to emphasize that the line `jupyter: julia-1.7` should be changed to the to the actual IJulia kernel version that is installed. The current stable version of Julia is 1.8.x.

- Please remind the reader that if they store the contents of the example script in a `.qmd` file and then place it in a subdirectory of an existing Julia project, let's call it `X`, then IJulia will default to the environment of `X` instead of the default Julia environment. Since the example script uses the Plots.jl library, it should be installed in `X` if the reader makes a `.qmd` file in a subfolder of `X`.

- Please provide suggestions or contact information as to how one can contribute towards developing a Pluto.jl notebook version of Quarto.

**Comment by cscheid** [comment]
Thanks for the suggestions.

> I have the following suggestions for [this help webpage](https://quarto.org/docs/computations/julia.html):

> * Please add an extra sentence near the first example script to emphasize that the line jupyter: julia-1.7 should be changed to the to the actual IJulia kernel version that is installed. The current stable version of Julia is 1.8.x.

That's a great idea, I just made the change. Thank you!

> * Please remind the reader that if they store the contents of the example script in a .qmd file and then place it in a subdirectory of an existing Julia project, let's call it X, then IJulia will default to the environment of X instead of the default Julia environment. Since the example script uses the Plots.jl library, it should be installed in X if the reader makes a .qmd file in a subfolder of X.

This is IJulia behavior, and not quarto behavior. We make a conscious decision to scope our webpage to quarto documentation, so this is out of scope.

> * Please provide suggestions or contact information as to how one can contribute towards developing a Pluto.jl notebook version of Quarto.

This is out of scope for the same reason as above.
