### ISSUE TITLE
Error in quarto-web/docs/authoring/figures.qmd

### ISSUE THREAD

**Issue by SamEdwardes** [quarto-dev/quarto-web#395]
## Current

https://github.com/quarto-dev/quarto-web/blob/e20cfc3a63ffe9405928e5dd21748e42acb90ad2/docs/authoring/figures.qmd#L71-L88

## Suggested change

There may be an error in the explanation. I think the wrong file extensions are referenced.

```markdown  
By default this will look for `elephant.svg`, however if you are rendering to PDF it 
will look for `elephant.tex`. You can customize this behavior using the 
`default-image-extension` option. For example:
```

**Comment by cscheid** [comment]
(sorry for the delay). Why do you think the wrong file extension is referenced? the default image extension for formats is `png` for non-pdf formats, and `pdf` for pdf formats.

**Comment by SamEdwardes** [comment]
Thank you @cscheid. One thing I am confused about:

- where does `elephant.png` come from? In the yaml the default image extension is `.svg`.
- where does `elephant.pdf` come from? THe default image extension for pdf docs is `.tex`.

 ``` yaml 
 format: 
   html: 
     default-image-extension: svg 
   pdf: 
     default-image-extension: tex 
 ```

**Comment by cscheid** [comment]
> where does elephant.png come from? In the yaml the default image extension for HTML is .svg.

That's the example that the [webpage](https://quarto.org/docs/authoring/figures.html) starts with:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/285675/203618007-954c6dda-7872-4e93-8171-dd27c5143b6e.png">

But I'm confused by your question in general. That yaml is telling you how to _change_ the default image extension, and set it to `svg` in the `html` format, and to `tex` in the `pdf` format. But the _default_ value, when not given by the yaml, is `png` for HTML formats, and `pdf` for pdf formats. That YAML example has nothing to do with that, right?

**Comment by SamEdwardes** [comment]
Thank you @cscheid. I understand now. The first sentence...

```markdown
By default this will look for `elephant.png`, however if you are rendering to PDF it will look for `elephant.pdf`.
```

assumes that you have not customized the behaviour. I think I was reading it wrong originally. Thank you for explaining.
