### ISSUE TITLE
Tab for pre-releases empty and respective download button not working on website

### ISSUE THREAD

**Issue by cathblatter** [quarto-dev/quarto-web#399]
A minor inconvenience:
on https://quarto.org/docs/download/ I see two tabs for downloading: 

<img width="400" alt="Bildschirmfoto 2022-09-18 um 07 43 45" src="https://user-images.githubusercontent.com/24943957/190887713-8b7b64bd-8f73-4d4c-8133-bdf0d4ce99f8.png">

Clicking on the tab for the pre-releases gives me an emtpy tab (on Firefox, Mac OS):

<img width="400" alt="Bildschirmfoto 2022-09-18 um 07 43 51" src="https://user-images.githubusercontent.com/24943957/190887747-5f3c8f0a-d414-423d-8fa6-75f1f9bb9e96.png">

Clicking on the (non-labelled) download button gives me 404 - page not found.

Of course, I can use the GH-release page for downloading but I think this is not something a typical end-user knows - I'd either remove the tab on the site, describe how to get to the GH-release page or fix the broken site/link.

As said - its a minor thing - thanks for your work, feel free to close if not relevant

**Comment by dragonstyle** [comment]
Thanks for letting us know - this is fixed!
