### ISSUE TITLE
Quarto <code> color 

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [quarto-dev/quarto-web#401]
Hello Quarto,

I am using Quarto theme Slate for a book project, 

I want to change the code color for all of my `<code>` or "``" such from purple (#9552B0) to another color.

![Screen Shot 2022-09-20 at 1 57 48 PM](https://user-images.githubusercontent.com/55933131/191352682-e93ef7c2-a2a0-4e76-bf72-86aa1cc7ef47.png)

I have tried 3 times to permanently change the color code in the css file. I find the `code{ }` and edit the hex value but as soon as i change page or save the page it goes back to default.

`./_book/site_libs/bootstrap/bootstrap.min.css`

<img width="600" alt="Screen Shot 2022-09-20 at 2 05 54 PM" src="https://user-images.githubusercontent.com/55933131/191354139-1f7de162-89e7-45b3-bddf-76a98b464f20.png">

is there a way I can do this or am i stuck with this purple?

**Comment by dragonstyle** [comment]
You can use SCSS variables to control this color. The variables controlling inline code are here:

https://quarto.org/docs/output-formats/html-themes.html#inline-code

something like:

```
format:
  html:
    theme:
      - custom.scss
      - slate
```

with the contents of custom.scss being:

```css
/*-- scss:defaults --*/
$code-color: red;
$code-bg: purple;
```
