### ISSUE TITLE
Instructions to use github actions to publish blog

### ISSUE THREAD

**Issue by castorfou** [quarto-dev/quarto-web#404]
as explained in documentation at https://quarto.org/docs/publishing/quarto-pub.html#github-action,
it is possible to have CI/CD handling publication to github pages and it requires `_publish.yml` file to do so.

It is asked to provide id and url. Url is clear to me but what is this id and where can I get it. 

```
This is the example from documentation:
- source: project
  quarto-pub:
    - id: "5f3abafe-68f9-4c1d-835b-9d668b892001"
      url: "https://njones.quarto.pub/blog"
```

thank you for your guidance

**Comment by cscheid** [comment]
As the documentation states, the ID will be generated for you by the `quarto publish` command.

**Comment by castorfou** [comment]
Thanks for the answer. I should have read more carefully!

For a reason I cannot complete at least one publish. I use a corporate PC that prevents it to run completely.
I have an open discussion about that at: https://github.com/quarto-ext/video/issues/27

**Comment by castorfou** [comment]
I can quarto publish using a non-corporate PC.
Site is published at github-pages.
But `_publish.yml` is not created.

**Comment by castorfou** [comment]
Ok I have understood my confusion.
I would like to use github actions to publish to github pages not quarto-pub.
And in that case we don't have _publish.yml.

I guess I can close this on and ask to community if someone has tried that

**Comment by jjallaire** [comment]
This is covered in the documentation here: https://quarto.org/docs/publishing/github-pages.html#github-action

**Comment by castorfou** [comment]
yes indeed. I have tried it this morning and everything ran smoothly. Thank you.
