### ISSUE TITLE
Update reference.ts to support new schemas

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-web#407]
I was trying to update the doc running `quarto run ./tools/reference.ts` but it seems it is out of date regarding the reorganization of schema in quarto-cli. 

I started looking into this but this is  probably an item you'll want to target as a whole for 1.2, and not update reference right away to pre-release version only.  So I am opening this to identify it that still need to be done.

This is needed to completely close #406 that we can't update with `quarto run ./tools/reference.ts` right now.

**Comment by dragonstyle** [comment]
This should be fixed now (and I regenerated the reference)

**Comment by cderv** [comment]
Oh awesome. Way quicker than me and clever solution 😅  That was very insighful to read your commit change after trying myself  yesterday evening as a quick (unsuccessful) typescript examples. 

Thank you!

**Comment by dragonstyle** [comment]
I had the benefit of being involved in most of these schema changes so I was pretty quickly able to figure out what was going on... I would say this typescript file Is not our best code 😆
