### ISSUE TITLE
quarto numbering not working

### ISSUE THREAD

**Issue by wleescor** [quarto-dev/quarto-web#410]
copying the example from https://quarto.org/docs/get-started/authoring/vscode.html
using rstudio cloud 
2022.07.1 Build 554.pro3
numbers don't show up in the headings
---
title: Quarto Basics
author: Norah Jones
date: 'May 22, 2021'
toc: true
number-sections: true
---

## Colors

-   Red
-   Green
-   Blue

## Shapes

-   Square
-   Circle
-   Triangle

## Textures

-   Smooth
-   Bumpy
-   Fuzzy
![image](https://user-images.githubusercontent.com/111639153/192081218-78aecbbc-e007-4d5b-a135-3562106d0d93.png)

**Comment by dragonstyle** [comment]
We aren't able to reproduce this. The source code from the example:

```markdown
---
title: Quarto Basics
author: Norah Jones
date: 'May 22, 2021'
toc: true
number-sections: true
---

## Colors

- Red
- Green 
- Blue

## Shapes

- Square
- Circle
- Triangle

## Textures

- Smooth
- Bumpy
- Fuzzy
```

produces:

<img width="1009" alt="Screen Shot 2022-09-25 at 9 07 16 AM" src="https://user-images.githubusercontent.com/261654/192145037-2c28b592-4130-49d5-9531-dc680b3b697b.png">
