### ISSUE TITLE
References are in appendicies not inside body when `refs` is used

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-web#424]
We should probably update the doc on this right ? 
![image](https://user-images.githubusercontent.com/6791940/193831133-c2d39b90-a6a2-4b54-8b92-c3a95905e3cd.png)

The sentence highlighted  does not make much sense because references are moved into bottom with appendices by default

Or does using `::: {#refs}` should live the references in the body ?

**Comment by dragonstyle** [comment]
This is a bug in Quarto! Fixed here and will resolve itself next website publish! Thank you for catching it!

https://github.com/quarto-dev/quarto-cli/commit/2d9cd52fe23402e7e41e9f754d7f070201134a17

**Comment by cderv** [comment]
Ok Good ! I wasn't sure it was a bug. 

I triggered a run and this is fixed indeed. I wouldn't have found the issue. Thanks !
