### ISSUE TITLE
Jupyter engine, clarify screenshot

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-web#430]
The screenshot at: https://quarto.org/docs/tools/rstudio.html#jupyter-engine

Doesn't have the engine: Jupyter selected, so it doesn't display all the available menu items.

It would be probably be better to alter the screenshot to something like the below:

![image](https://user-images.githubusercontent.com/29187501/194574853-330d96fd-1a5a-4e5a-b868-0ea7feb34424.png)

**Comment by jjallaire** [comment]
Thanks! Done here: https://github.com/quarto-dev/quarto-web/commit/d0148f18b375ee3579983cec775a6120679ee51b
