### ISSUE TITLE
Quarto tries to use Julia version 1.7 but I am running 1.8.2

### ISSUE THREAD

**Issue by rambunctiousapple** [quarto-dev/quarto-web#434]
I followed the Quarto getting started tutorial and installed Quarto and the VSCode Quarto extension. When I hit the render pdf button I see this:

```
PS C:\Users\seatt\Source\Quarto> quarto preview c:/Users/seatt/Source/Quarto/src/tutolrial.qmd --to pdf --no-browser --no-watch-inputs

Starting julia-1.7 kernel...ERROR: 

Kernel didn't respond in 60 seconds
```
I'm running Julia 1.8.2. It looks like the Julia kernel version is hardcoded into Quarto and it is not looking for the latest version of Julia. Is there a way to get Quarto to use the latest version of Julia?

**Comment by jjallaire** [comment]
Unfortunately Julia installs a different kernel for each version on your machine. We don't hardcode the Julia kernel version at all, rather it looks like it is discovering a Julia 1.7 kernel that doesn't work for whatever reason. If you run the `quarto check` command you'll see all of the available kernels (you can see I have two Julia kernels):

```bash
[✓] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
      Jupyter: 4.7.1
      Kernels: ir, julia-1.7, bash, julia-1.5, python3, c

[✓] Checking Jupyter engine render....OK
```

You can then choose an explicit kernel using the `jupyter` option as shown here: https://quarto.org/docs/computations/julia.html#kernel-selection

**Comment by rambunctiousapple** [comment]
`quarto check` returns this:
```
PS C:\Users\seatt> quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.251
      Path: C:\Users\seatt\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: C:/Users/seatt/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.11.1
      Kernels: julia-1.7, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
But `juliaup status` returns this:
```
PS C:\Users\seatt> juliaup status
 Default  Channel  Version      Update
---------------------------------------
          rc       1.8.2+0.x64
       *  release  1.8.2+0.x64
```
Any idea why `jupyter` is finding a 1.7 kernel on my machine when I don't appear to have Julia 1.7 installed? Any suggestions about how to troubleshoot this?

Tried choosing an explicit kernel as you suggested. Here's my .qmd file:
```
---
title: "Plots Demo"
author: "Brian Guenter"
date: "5/22/2021"
format:
  html:
    code-fold: true
jupyter: julia-1.8
execute: 
  enabled: true
reference-location: margin
---
```
When I try to render the file I get this error message:
```
PS C:\Users\seatt\Source\Quarto> quarto preview c:/Users/seatt/Source/Quarto/src/tutolrial.qmd --to pdf --no-browser --no-watch-inputs
ERROR: Jupyter kernel 'julia-1.8' not found.
```
