### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by rsilveirafh** [quarto-dev/quarto-web#440]
Hello there, just to point out that the second elephant is pointing to **https://quarto.org/quarto.org**, when it should be **https://quarto.org**.

![Screenshot from 2022-10-12 19-48-11](https://user-images.githubusercontent.com/8616924/195462446-4509f2ad-335e-4b8c-8d6e-b3131c2a445e.png)

Thanks!

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/quarto-dev/quarto-web/commit/8b4e1dc49fb3d9c5da12bb09ef89f70007b7b2af
