### ISSUE TITLE
HTML Code Blocks page: text not rendered in the current version of the manual

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-web#448]
Hi,
in that code page there is a note about "Code line numbers", but it's not rendered in [the manual](https://quarto.org/docs/output-formats/html-code.html).

Is it normal?

![image](https://user-images.githubusercontent.com/30607/195976676-921bf532-f74d-4cd2-8345-a67e03b0bd57.png)

**Comment by jjallaire** [comment]
Thanks! The problem was that edits to the qmd made w/o local rendering weren't getting picked up in CI (b/c they were subject to `freeze` and CI uses only already frozen content). I've made an update here that is fully rendered: https://quarto.org/docs/output-formats/html-code.html#line-numbers

**Comment by aborruso** [comment]
Thank you
