### ISSUE TITLE
Text not rendered in the quarto documentation

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-web#451]
Hi,
in the [article layout page code](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/article-layout.qmd), there is a portion of text not rendered (highlighted in red below).

@jjallaire I think it happens for the same reason of [this](https://github.com/quarto-dev/quarto-web/issues/448#issuecomment-1279828994).

Thank you

![image](https://user-images.githubusercontent.com/30607/196273985-35f2a1c6-09a0-4e28-96c6-0e8c64f9f530.png)

**Comment by jjallaire** [comment]
Thanks! Just re-rendered so it should show up on the next publish.

**Comment by aborruso** [comment]
> Thanks! Just re-rendered so it should show up on the next publish.

@jjallaire some times I edit a qmd file during a `preview` mode. I save it, I reload the web preview but I have the old output.

And also for me the only way is to render all and then restart with preview.

Is there a way to force the new render of the file I'm editing during the preview mode?

Thank you
