### ISSUE TITLE
Wrong formatting on revealjs page

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-web#452]
This page has a problem with the formatting under the Line Highlighting section: https://quarto.org/docs/presentations/revealjs/#code-blocks

(although I couldn't spot the problem in the .qmd file)

<img width="1098" alt="Screen Shot 2022-10-19 at 11 54 25" src="https://user-images.githubusercontent.com/25734232/196755778-b87bc0a9-870b-426c-97a4-17b8d4a9cbd7.png">

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto-web/commit/54037479e72a44319ba0ab45e4f9c3559f995d7f
