### ISSUE TITLE
Documentation outdated in HTML features

### ISSUE THREAD

**Issue by normansimonr** [quarto-dev/quarto-web#455]
Hi! Quarto enthusiast here!

Just to let you guys know that the text here: https://quarto.org/docs/output-formats/html-basics.html#self-contained

Says that one must use `self-contained: true` to generate a standalone HTML with no dependencies, but the [reference](https://quarto.org/docs/reference/formats/html.html#rendering) says this option has been deprecated in favour of `embed-resources`.

Thanks!

**Comment by jjallaire** [comment]
Thanks! Addressed here: https://github.com/quarto-dev/quarto-web/commit/6077f81ac7329267318618f1c6bb46eb00a0e5d3
