### ISSUE TITLE
There seems a spelling mistake.

### ISSUE THREAD

**Issue by lazychoi** [quarto-dev/quarto-web#468]
Many users have reported problems with using quarto publish gh-pages on Windows systems. We are investigating and hoping to have a fix for this soon, but **it the meantime** we recommend against using quarto publish gh-pages on Windows (rather, try using the [Render to docs](https://quarto.org/docs/publishing/github-pages.html#render-to-docs) workflow described above).

There seems a spelling mistake. : it the meantime ⇒ in the meantime

**Comment by jjallaire** [comment]
Thanks! Just fixed.
