### ISSUE TITLE
Error: Unknown option "--no-browse". Did you mean option "--no-render"?

### ISSUE THREAD

**Issue by Sdemaeyer2** [quarto-dev/quarto-web#48]
Was just trying out to apply the option to write a book making use of the RStudio IDE and a Quarto book project. When trying to render the book (I just added some content in the introduction file I get the following error thrown:

ERROR: Error: Unknown option "--no-browse". Did you mean option "--no-render"?

Potentially something goes wrong as I was copy pasting content from an rmarkdown file made in bookdown?

**Comment by jjallaire** [comment]
This got changed to `--no-browser` at some point. Try updating to the daily build of RStudio (https://dailies.rstudio.com) and it should work fine.

**Comment by Sdemaeyer2** [comment]
Yes! Works perfect now. Sorry for throwing this question here. Had to read the documentation better. THX!!
