### ISSUE TITLE
cookie-preferences

### ISSUE THREAD

**Issue by patzaw** [quarto-dev/quarto-web#486]
Hi

In this section https://quarto.org/docs/websites/website-tools.html#cookie-preferences, I think that the brackets in the code must be replaced by curly brackets:

`[cookie preferences](#open_preferences_center)` --> `[cookie preferences]{#open_preferences_center}`

That's what I did to make it work.

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/quarto-dev/quarto-web/commit/192fd3fc76ec7fbc50d066a3b8ca4d9867b28053
