### ISSUE TITLE
Full text search does not work in a published html book

### ISSUE THREAD

**Issue by zhilinsu** [quarto-dev/quarto-web#490]
Hello, 

I used RStudio to create an HTML book and published it using Terminal. In the preview version of the book in RStudio, I can used the full text search properly but in the HTML file in the _book directory, the full text search does not work. I have tried several ways to adjust the .yml file but all failed. I was wondering whether there would be any reasons for this issue and if you would mind giving me some advice. Many thanks!

**Comment by dragonstyle** [comment]
If you are merely opening the HTML file locally (not using a web server) with a `file://` URL, javascript will not execute. The ages need to be served from an HTTP url in order for search to work properly.

If that isn't it, can you share some additional information about what you're seeing (and perhaps share a link to the deployed website with the search not working)?

**Comment by zhilinsu** [comment]
@dragonstyle Thank you so much! I've deployed the website to Netlify, and everything works smoothly now.
