### ISSUE TITLE
Adding margin-column makes TOC links navigate to obscured titles

### ISSUE THREAD

**Issue by cdavisurban** [quarto-dev/quarto-web#499]
I noticed on the quarto website that when clicking on the table of contents on pages with margin-columns, the links navigate the page such that the navbars obfuscate the titles of those sections. I have replicated this within my own quarto documents and believe it has something to do with the margin-columns. 

Does anyone else notice the same thing? Is this a known bug?

**Comment by dragonstyle** [comment]
I just made a change which should fix this - will regenerate the site with the fix shortly!

**Comment by cdavisurban** [comment]
@dragonstyle Thanks so much for looking into this!!

Has the site regenerated yet? If so, just a flag that I'm still seeing the problem at https://quarto.org/docs/authoring/article-layout.html. For what it's worth, I believe the issue is with quarto itself and is not specific to this website, as I have the same problem within my own quarto documents.

**Comment by dragonstyle** [comment]
The changes are present in Quarto `1.3.20` and the site was just deployed using this version. Give it a try and let us know if this improves things...

**Comment by cdavisurban** [comment]
@dragonstyle amazing!!! Works perfectly, thanks so much for following up on this. Really appreciating quarto and all the work that you all put into this!
