### ISSUE TITLE
quarto add is not working for me

### ISSUE THREAD

**Issue by Izar-de-villasante** [quarto-dev/quarto-web#514]
Apparently quarto-cli understands quarto install extension  command and beahaves as documented in the post for quarto add. 
So when I try: 
  `quarto add quarto-ext/fontawesome` 
I get:
ERROR: Unknown command "add". Did you mean command "run"?
If I use:
 `quarto install extension quarto-ext/fontawesome` 
it works as expected.

I have been using different versions of quarto-cli, currently I am using v.1.1.189 but it was always the same, regardless of the version I tried.

**Comment by jjallaire** [comment]
This only works in >= v1.2 (I see that you are running v1.1.189)
