### ISSUE TITLE
Quarto can't compile `python` code and `R` code in the same document

### ISSUE THREAD

**Issue by desautm** [quarto-dev/quarto-web#518]
I can render both code chunks separatly but I can't render them in the same document. Here is my minimal file.

````
---
title: "Python and R"
format: html
---

## Python

```{python}
print("Hello world")
```

## R

```{r}
mean(mtcars$mpg)
```
````

Here is the error message I receive:

````
Erreur dans py_initialize(config$python, config$libpython, config$pythonhome,  :
  python38.dll - Le module spécifié est introuvable.
Appels : .main ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Exécution arrêtée
````

**Comment by cscheid** [comment]
That's reticulate telling you that `python38.dll` needs to be in your path in order for it to be able to run Python cells.

**Comment by desautm** [comment]
I'm using Python 3.11 and not Python 3.8. Is that the problem? Should I revert to an older Python distribution? Thanks.

**Comment by cscheid** [comment]
I'm not sure. I'd be very surprised if reticulate didn't support 3.11. It's possible that you're running an old version of reticulate and need to upgrade your R libraries, or your R installation more generally.
