### ISSUE TITLE
Is Windows caution for gh-pages still necessary?

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-web#527]
Looking through issues, I see that quarto-dev/quarto-cli#1524 was solved, which makes me wonder if this is still operative:

https://github.com/quarto-dev/quarto-web/blob/2c614fa1706829ac4a8e8ddae54126cb22891d0e/docs/publishing/github-pages.qmd#L65-L69

Of course, I could be missing something. 

Happy to make a PR to take it out - thanks!

**Comment by jjallaire** [comment]
I think it is indeed no longer required. PR would be great, thanks!

**Comment by ijlyttle** [comment]
Great news! PR forthcoming
