### ISSUE TITLE
label fig

### ISSUE THREAD

**Issue by wleescor** [quarto-dev/quarto-web#529]
After a lot of trial and error, I worked out that 
#| label: 
tag names must have a fig- in front of it for the caption to auto render. There is no error message or documentation about this, so would be useful for users to know about this at least in the documentation on the web page

Thanks

**Comment by jjallaire** [comment]
We do mention this requirement a number of times in the docs on cross-references: https://quarto.org/docs/authoring/cross-references.html

But perhaps there are other places we should be highlighting? Let us know what you think.

**Comment by wleescor** [comment]
Thanks for your speedy response!

Something like this page with a big red warning box: https://quarto.org/docs/authoring/tables.html
"Label Prefix
In order for a table to be cross-referenceable, its label must start with the tbl- prefix."
would have been helpful

but if we put on this webpage for figure captions: https://quarto.org/docs/authoring/figures.html

I didn't see the cross-reference page when trying to figure out how to put in a caption using quarto.
Just a suggestion.

**Comment by jjallaire** [comment]
Apologize for the delay over the holidays! Updated docs based on your suggestions are here: https://quarto.org/docs/authoring/figures.html#cross-references
