### ISSUE TITLE
Solution for ERROR: Error: Unknown option "--no-browse". Did you mean option "--no-render"?

### ISSUE THREAD

**Issue by zawkzaw** [quarto-dev/quarto-web#53]
When I run a quarto book project it show 

ERROR: Error: Unknown option "--no-browse". Did you mean option "--no-render"?

Could you please suggest a solution?

Thanks in advance.

**Comment by jjallaire** [comment]
This is likely because you are running an older version of Quarto OR and older version of RStudio.

Try updating to the latest version of the RStudio daily build (https://dailies.rstudio.com) and the latest version of Quarto.
