### ISSUE TITLE
Title Block Templates

### ISSUE THREAD

**Issue by directknowledge** [quarto-dev/quarto-web#535]
Where are the title block templates (ejs)?

I found this 
listing:
  template: gallery.ejs
here:
https://quarto.org/docs/websites/website-listings-custom.html#listing-templates

But I can not find out how I can customize the title-block for html. 

All I found was this:
https://quarto.org/docs/authoring/title-blocks.html

Is there something I'm missing?

Thank You.

**Comment by dragonstyle** [comment]
Title block templates are not implemented using EJS - they are using Pandoc native templates. The documentation you found on title blocks is correct. Can you say more about what you're trying to accomplish and we can steer you in the right direction?
