### ISSUE TITLE
"On this Page" 

### ISSUE THREAD

**Issue by zawkzaw** [quarto-dev/quarto-web#54]
When I run a quarto book project, on TOC page Output files  first appear "On this Page" 

Could you please suggest on how to remove it?

Thanks in advance.

**Comment by jjallaire** [comment]
This should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/0f26ba31b06b40bfcdba3633d670d0f0b8345560

For books you will now see "Table of contents" rather than "On this page"

**Comment by zawkzaw** [comment]
Thank you so much. The problem has been solved now with newer version of Quarto.
