### ISSUE TITLE
Figures page missing information on figure resizing

### ISSUE THREAD

**Issue by ralmond** [quarto-dev/quarto-web#545]
I used the following code to include a figure in my document (to be rendered as a web page):

```
![FOSS](https://upload.wikimedia.org/wikipedia/commons/3/31/Free_and_open-source_software_logo_(2009).svg)
```

But the resulting image was too large.  

What I would like to do is something like:
```
![FOSS](https://upload.wikimedia.org/wikipedia/commons/3/31/Free_and_open-source_software_logo_(2009).svg){fig-width="1in"}
```
To scale the figure.  

If such a switch exists, it should be documented on the Figures page.

**Comment by ralmond** [comment]
By hacking around, I found out what I wanted was `{width="1in"}`, but it should still be documented.

**Comment by jjallaire** [comment]
Thanks for the feedback! Updated docs are here: https://quarto.org/docs/authoring/figures.html#figure-sizing
