### ISSUE TITLE
Something seems to be off with the Quarto documentation

### ISSUE THREAD

**Issue by novotny1akub** [quarto-dev/quarto-web#563]
![image](https://user-images.githubusercontent.com/39886440/212269515-081aca14-0ad5-4525-9e7b-7af252c4186e.png)

**Comment by novotny1akub** [comment]
This example used to be a beautiful presentation showing the goodies of Quarto for presentations. Currently it seems like the styles are not applied.

**Comment by dragonstyle** [comment]
Thanks for letting us know - I'm taking a look now!
