### ISSUE TITLE
GitHub actions/checkout@v2 no longer supported

### ISSUE THREAD

**Issue by TylerHillery** [quarto-dev/quarto-web#569]
In the example `.github/workflows/publish.yml` provided in the quarto docs, it uses the ` actions/checkout@v2`. I got an error today saying 
> [build-deploy](https://github.com/TylerHillery/TylerHillery.github.io/actions/runs/3924565694)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Once I updated to `actions/checkout@v3 ` the build worked. I will provide a PR to update the docs.

**Comment by cscheid** [comment]
Do note that "deprecated" and "no longer supported" are not synonyms.

**Comment by cscheid** [comment]
The error you're seeing in that action appears to come from the `social-share` filter:

```
Error running filter social-share:
Could not find executable social-share
```

**Comment by TylerHillery** [comment]
Ah thank you for pointing the difference between "deprecated" and "no longer supported". I got confused because the true error that was causing the build to fail was the `could not find executable social-share` as you pointed out. That was just because I wasn't the _extensions dir. I appreciate the feedback.
