### ISSUE TITLE
Can't find options to start a new Quarto Project indaily build of RStudio as specificed on the website

### ISSUE THREAD

**Issue by Speldosa** [quarto-dev/quarto-web#57]
On [this page](https://quarto.org/docs/tools/rstudio.html), it says that if you're using the daily build of RStudio, you'll get an option to create a new Quarto document by using `File > New File > Quarto Document`. However, I've downloaded the daily build on MacOS (I've pasted the version info below), and I can see no such option. I can't find an option for Quarto Projects through the `File > New Project > New Directory > Quarto Project` route either.

**Version info:**
RStudio 2022.02.0-preview+393 "Prairie Trillium" Preview (d0c4553a63011f8254855442920168169222c306, 2022-01-23) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by jjallaire** [comment]
If you have Quarto installed on the system RStudio _should_ be finding it and lighting up that command. Perhaps it isn't able to see it on the `PATH` for some reason?

Note that RStudio daily build also has an embedded version of Quarto which you can enable via the R Markdown preferences pane (this will definitely work and not be subject to any `PATH` discovery issues):

<img width="591" alt="Screen Shot 2022-01-24 at 7 26 36 AM" src="https://user-images.githubusercontent.com/104391/150783007-68bbad49-7b78-498d-b64f-295954dee077.png">

**Comment by Speldosa** [comment]
Oh, thanks. I didn't realize you had to install the Quarto CLI or enable Quarto in RStudio before you could find it. It works now. I don't know if you want to update the description on the linked page to accommodate future dum-dums like myself :)

**Comment by jjallaire** [comment]
Good point! Added those docs here: https://quarto.org/docs/tools/rstudio.html
