### ISSUE TITLE
quarto publish error

### ISSUE THREAD

**Issue by Solab5** [quarto-dev/quarto-web#578]
![quarto](https://user-images.githubusercontent.com/78223861/213518777-ce441626-9e6f-40be-a51a-c0179d1be9cf.PNG)

I am trying to use the terminal to upload to github pages, but this is what I am getting
ERROR: PermissionDenied: Permission denied (os error 13), rename '/home/morris/git/Blogsite/site_libs' -> '/home/morris/git/Blogsite/_site/site_libs'

**Comment by cscheid** [comment]
Is it possible that you previously ran the quarto command with increased privileges? It looks like `/home/morris/git/Blogsite/site_libs` already exists but you don't have permission to move it.

**Comment by Solab5** [comment]
> Is it possible that you previously ran the quarto command with increased privileges? It looks like `/home/morris/git/Blogsite/site_libs` already exists but you don't have permission to move it.

ohhh, does it mean that I have to change permission, chmod stuff

**Comment by cscheid** [comment]
For example, or just delete that folder (I'm assuming you didn't create `site_libs` yourself - please don't accidentally delete content you wrote yourself!)

**Comment by Solab5** [comment]
Actually, I added the user executable permission on .gitignore file, It ran but the deployment is taking way too long

**Comment by Solab5** [comment]
every thing worked after closing my local preview and removing _site
