### ISSUE TITLE
Inline code not rendering correctly inside table cells

### ISSUE THREAD

**Issue by Jreade89** [quarto-dev/quarto-web#580]
When attempting to render inline code (e.g., `r variable_one`) inside of a table cell, the output is literally "`r variable_one`" instead of the referenced value. This is only a problem when inside a table cell. 

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
RStudio Version 2022.12.0+353 (2022.12.0+353)
knitr version 1.40

Any suggestions are appreciated. Thank you!

**Comment by cscheid** [comment]
This is not a bug; knitr doesn't know that you mean to use a variable in those contexts. Instead, write the expression you want to a variable, and then construct the table programmatically.
