### ISSUE TITLE
Inconsistent variable name for fontsize?

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-web#59]
On this [page](https://quarto.org/docs/output-formats/html-themes.html) the documentation references a `fontsize` variable, while the code example below uses `font-size`. I believe that `fontsize` is correct, because using `font-size` didn't work on my document, although it didn't raise an error. 

See attached screenshot:

<img width="796" alt="Screen Shot 2022-01-30 at 12 25 29 PM" src="https://user-images.githubusercontent.com/25734232/151712446-a7f6b5cd-b41d-4a9a-b025-6191c8f7fab3.png">

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto-web/commit/06ab931bd2b6cdf737807c40d92c3b0b1a9cedaa
