### ISSUE TITLE
Error including  shiny app in quarto website

### ISSUE THREAD

**Issue by asalber** [quarto-dev/quarto-web#590]
Hi!
I want to incluye a small Shiny app in a page of a website generated with quarto. To reproduce the error, create a new quarto website project with Rstudio.
This is the source code of the `index.qmd` file.

````
---
title: "Old Faithful"
format: html
server: shiny
---

```{r}
sliderInput("bins", "Number of bins:", 
            min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r}
#| context: server
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```
````

And this is the `_quarto.yml` generated by default by Rstudio.
````
project:
  type: website

website:
  title: "web-shiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

When I render de website, I get the error
```
Error in shiny_prerendered_html(input_rmd, render_args) : 
  Prerendered HTML file not found at /run/media/tmp/quarto/web-shiny/index.html
Calls: .main ... <Anonymous> -> shiny_prerendered_app -> shiny_prerendered_html
Execution halted
```

I use quarto version 1.2.313 and Rstudio version 2022.12.0 Build 353.

**Comment by cscheid** [comment]
Take a look at https://quarto.org/docs/interactive/shiny/index.html, which covers the differences between a regular quarto site and a shiny application. The short of it is you can't use `server: shiny` as part of a website; `server: shiny` indicates an application that needs to be run on a server, and that's not what a website is.

**Comment by asalber** [comment]
Sorry for the duplicated question.
I read that page, and it is true that it talks about quarto documents, not websites, but I think an explicit warning about that it is not possible to generate a page of a website this way, could help. 
Thank you!

**Comment by cscheid** [comment]
@asalber That's a fair point.

I'll open an issue to track.
