### ISSUE TITLE
Documentation suggests using `git reset --hard` without explaining consequences

### ISSUE THREAD

**Issue by mattwigway** [quarto-dev/quarto-web#617]
The [documentation for creating a `gh-pages` branch to publish to](https://quarto.org/docs/publishing/github-pages.html#source-branch) suggests running `git reset --hard`, which will discard uncommitted changes. The page should at least note this consequence, or maybe suggest `git reset --mixed` which removes anything staged for commit but doesn't touch the working tree, which I think is the goal here.

**Comment by cscheid** [comment]
We warn users about this in the previous paragraph:

> First, make sure you have commited all changes to your current working branch with git status.
