### ISSUE TITLE
is python-markdown nbextension supported in quarto rendering?

### ISSUE THREAD

**Issue by mdbjr** [quarto-dev/quarto-web#618]
Hi, 

I am using Quarto to render a jupyter notebook to docx.

I used the python-markdown nbextension for jupyter notebook to pass a python variable in a markdown cell.

Here is my example:
<span style="color:black;font-family:baskerville;font-size:32px">Weekly Market Update - {{date_str}}</span>

date_str is a variable containing the string "January 1, 2023"

When I render this in the Jupyter notebook cell, it behaves as expected.  But in the docx file that is rendered by Quarto, I just see {{date}} printed.

Is there some limitation in Quarto that it cannot support the nbextension?

Thanks

**Comment by jjallaire** [comment]
Yes, this is a Jupyter notebook front-end extension so not something that Quarto has access to.

There is ongoing work and discussion about creating a standard way for front ends and rendering engines like Quarto and nbconvert to evaluate markdown expressions, but there isn't anything yet broadly agreed upon.

In the meantime, one thing that is less elegant but would work in both Jupyter and Quarto is explicit output of Markdown. See docs on this here: https://quarto.org/docs/computations/execution-options.html#jupyter
