### ISSUE TITLE
RSS Feed and Category Feed content links exist but the sections are missing

### ISSUE THREAD

**Issue by fortunewalla** [quarto-dev/quarto-web#630]
On this page, https://quarto.org/docs/websites/website-blog.html

The below links are to sections RSS Feed and Category Feeds which don't exist. 

https://quarto.org/docs/websites/website-blog.html#rss-feed 

https://quarto.org/docs/websites/website-blog.html#category-feeds

Have they been removed or shifted elsewhere?

**Comment by dragonstyle** [comment]
I'm not following the issue that you're seeing - When I follow those links:

https://quarto.org/docs/websites/website-blog.html#rss-feed
https://quarto.org/docs/websites/website-blog.html#category-feeds

The content is present - is that not what you are seeing?

**Comment by fortunewalla** [comment]
> 

Hi, Thanks for the quick response.

I was using Firefox. Just now I tested in on Edge and it works there. Also I tried in Firefox Safe mode and it works. I disabled the script blocker but it stills doesn't show up in normal mode. 🤔

As seen below, There is Themes and then there is Publishing but the RSS Feed & Category Feed content is missing.

![image](https://user-images.githubusercontent.com/7158596/219749561-c335c85f-5912-45c1-8814-0cec77d911cf.png)

### It seems to be grayed out in Firefox.

![image](https://user-images.githubusercontent.com/7158596/219752417-242ad456-1971-4dca-ad93-3b54a81523f5.png)

### Expansion

![image](https://user-images.githubusercontent.com/7158596/219752769-1c5aabe9-7ffe-4dcb-9854-5b4bbb8dc322.png)

**Comment by fortunewalla** [comment]
> 

Hi, Thanks for the quick response.

I was using Firefox. Just now I tested in on Edge and it works there. Also I tried in Firefox Safe mode and it works. I disabled the script blocker but it stills doesn't show up in normal mode. 🤔

As seen below, There is Themes and then there is Publishing but the RSS Feed & Category Feed content is missing.

![image](https://user-images.githubusercontent.com/7158596/219749561-c335c85f-5912-45c1-8814-0cec77d911cf.png)

### It seems to be grayed out in Firefox.

![image](https://user-images.githubusercontent.com/7158596/219752417-242ad456-1971-4dca-ad93-3b54a81523f5.png)

### Expansion

![image](https://user-images.githubusercontent.com/7158596/219752769-1c5aabe9-7ffe-4dcb-9854-5b4bbb8dc322.png)

**Comment by dragonstyle** [comment]
I'm not sure what the cause of this could be- I still can't reproduce it locally with any browser. Is it possible you've taken some action within that Firefox browser to hide those nodes? We aren't doing anything to hide those nodes and we haven't really changed that content in the last several months, so I can't really explain why you would be seeing this.

**Comment by fortunewalla** [comment]
Sure. I understand. I will close this since it only breaks my setup and works across other browsers. 

Most of the documentation pages work except this particular section. I guess it must be a browser thing.

Thanks for investigating. 🙏🏼
