### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-web#69]
This link seems broken.

https://github.com/quarto-dev/quarto-web/blob/c6b25918db01e6f9701948b012d1c985641aa390/docs/authoring/cross-references.qmd#L187

https://quarto.org/docs/authoring/cross-references.html

![image](https://user-images.githubusercontent.com/50911393/153859158-7f9ef5a1-7a3c-405b-9653-1e167cea08c3.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @eitsupi Can I fix this?

**Comment by jjallaire** [comment]
Thanks! Just fixed.
