### ISSUE TITLE
Full layout issue

### ISSUE THREAD

**Issue by schrink** [quarto-dev/quarto-web#86]
When I clone this repo and render it locally (`quarto preview`) I don't get a full-width layout anywhere... 

<img width="1114" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/2532619/156877700-3f628622-efd6-45f0-bc43-f297e2c682c0.png">

What would be the reason for this?

**Comment by jjallaire** [comment]
It could be the version of Quarto you are running? What is the output of `quarto --version` ?

**Comment by schrink** [comment]
> It could be the version of Quarto you are running? What is the output of `quarto --version` ?

It is 0.3.43

**Comment by schrink** [comment]
Yes, that was the reason. I don't know how I got such an old version, I installed it only a few weeks ago. 
Thank you!
